# Generated by Django 4.1.13 on 2024-05-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'your_collection_name',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
